name: Job Notifier

on:
    workflow_dispatch: 
    schedule:
      - cron: '0,30 9-19 * * *' 
      - cron: '0 23 * * *'

jobs:
  run-job-notifier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Attempt to download the artifact
      - name: Check if todayoffers artifact exists and download
        id: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: todayoffers
          path: ./  # Downloads the artifact to the current directory
        continue-on-error: true  # Allow the job to continue even if the artifact is missing

      - name: Run Script
        run: python job_notifier.py

      # Upload the artifact if it doesn't exist or after the script is run
      - name: Upload todayoffers artifact
        uses: actions/upload-artifact@v3
        with:
          name: todayoffers  # Artifact name
          path: todayoffers.json  # Path to the file to upload